version: '2'
services:
    web:
        build: .
        container_name: "basercms_apache"
        ports:
            - "8080:80"
        volumes:
            - "./basercms:/var/www/html"
        links:
            - "db"
    db:
        image: mysql:latest
        container_name: "basercms_mysql"
        environment:
            - "MYSQL_ROOT_HOST=%"
            - "MYSQL_ROOT_PASSWORD=root"
            - "MYSQL_DATABASE=basercms"
            - "MYSQL_USER=basercms"
            - "MYSQL_PASSWORD=basercms"
        ports:
            - "3306:3306"
        volumes:
            - "./mysql:/var/lib/mysql"
        command: "mysqld --character-set-server=utf8 --collation-server=utf8_bin"
